### PR TITLE
Make code reusable

### PR DESCRIPTION
**Pull request by rominf**
Changes:
1. I've updated `README.md` to help users use this project.
2. I moved almost all the code to functions so that anybody could use it in their projects. Functions take all required arguments to get the work done. They also don't print anything. Also, they do not rely on `starter_oauth.config`.
3. I used those functions to preserve the console script functionality of `jira-oauth-generator`.
4. I've packaged this project with https://poetry.eustace.io/ and generated with it `setup.py`.

### CODE REVIEW

**Comment by rkadam** [comment]
Roman -- Thank you for the pull request. I haven't use Toml before. If you can add more details on how these changes will help to get jira-oauth-generator that will be very helpful.

Definitely going to learn more from you. Thank you again.
Raju

**Comment by rkadam** [comment]
did you update README.md? I don't see any updates in it. Can you please
make sure you checked in new changes?
Once I receive the updated version, will try to run it on your fork and see
how it goes.

Thank you again,
Raju

**Comment by rominf** [comment]
> did you update README.md?
By updating description I meant update of this PR description. But README.md is also updated: https://github.com/rkadam/jira-oauth-generator/pull/2/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by rkadam** [comment]
Roman -- Thank you for updates. I've seen your updated Pull request. It does help to understand things are that are changed as part of this code updates.

Now I'm trying to set up "jira-oauth-generator" as the first time user from your fork.
* I've created python 3 virtual environment
* I installed all libraries (pip install -r requirements.txt)
* Next what I'm supposed to do?
  * Running "python setup.py" throws me an error.
  * Are we supposed to use any commands using Poetry (sorry I've very little knowledge about this tool) to install this as a python module?
  * Otherwise now as a user of this tool, I'm not sure how to perform OAuth Dance (after Jira Administrator sets up Application link).

I hope you understand the problem now. Any guidance here would be helpful on how you are carrying out oAuth dance steps after cloning this repo.

Thank you again for your kind input,
Raju

**Comment by rominf** [comment]
I reimplemented this using classes, `aioify` and `aiohttp`. I won't maintain your fork anymore. See https://github.com/rominf/jira-oauth

**Pull request closed without merging**
